### ISSUE TITLE
error code 100 "could not find the program"

### ISSUE THREAD

**Issue by Icing-weaponry** [sks316/bcml-steamdeck#1]
Hi there,
I stumbled on your scripted randomly while looking for a tutorial and I gave it a shot.
I installed miniconda from this [link](https://docs.conda.io/en/latest/miniconda.html) and I chose the [Miniconda3 Linux 64-bit](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh) version.

After the install was complete I ran your script and after it was done I clicked on the desktop icon, unfortunatly I'm then greeted with the following error message.

"Unknown error code 100
Could not find the program '/home/deck/miniconda3/bin/bcml'
Please send a full bug report at https://bugs.kde.org/."

Obviously, it means it point to nothing, I had a look and indeed BCML isn't in the 'miniconda3/bin' folder.
Now I'm unsure where else would BCML would be (not verrryyy linux savy I’m afraid)

Thank you for your time,

**Comment by sks316** [comment]
```
~/miniconda3/bin/python -m bcml
```
Can you run this in Konsole and tell me if it launches BCML?

**Comment by Icing-weaponry** [comment]
thank you for the fast reply, I gave it a go and unfortunately I get the following response.
"/home/deck/miniconda3/bin/python: No module named bcml"

**Comment by sks316** [comment]
That means BCML wasn't installed at all. Can you try running the script again?

**Comment by Icing-weaponry** [comment]
allright ran the installer again, I got the pop up at the end that the installer has completed.
Tried the open the shortcut to the desktop, no dice.
I saved the whole konsole text when I try to run the installer
maybe that can give you a better clue why it didn't install.
thank you again
[bcml install output.txt](https://github.com/sks316/bcml-steamdeck/files/9347825/bcml.install.output.txt)

**Comment by sks316** [comment]
The install log was very helpful, thank you!
I've uploaded a fix, can you try running the script one more time?

**Comment by Icing-weaponry** [comment]
I ran the installed again, I'm guessing (and hopefully didn't make a mistake) that I didn't need to download it again.
Anywho I ran the same script and once again same error when I tried to open the desktop link and sure enough no bcml in the bin folder either.
Here's the new install log after your changes.
[bcml.install output 2.txt](https://github.com/sks316/bcml-steamdeck/files/9348144/bcml.install.output.2.txt)

**Comment by sks316** [comment]
Can you reinstall Miniconda, but using the version for Python 3.7 instead? I recognize this error and suspect this may fix your problem.

**Comment by Icing-weaponry** [comment]
you're right, that fixed it!
thank you very much now just gotta port my mods over to the deck!
Thanks again!

**Comment by sks316** [comment]
You're so welcome, I live to help others!
If anyone else you know has problems installing BCML on their Deck, please point them towards this script. The sole reason I made it was to help others.

**Comment by Icing-weaponry** [comment]
will do!
