### ISSUE TITLE
bcml Wont launch game or Cemu

### ISSUE THREAD

**Issue by MorgotheDestroyer** [sks316/bcml-steamdeck#10]
Forgive my ignorance. This is my first foray into GitHub and modding a game on my steam deck. The process seemed to be going perfectly, with BCLM installed without a hitch. As were multiple mods. 

However, I noticed that BCML was not showing in CEMU for available mods for breath of the wild. When returning to BCML I get green check marks for all locations including CEMU install, but when attempting to launch the game from BCML nothing happens and then from the drop down when I try to start CEMU without starting the game I received the following error:

Traceback (most recent call last):
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/_api.py", line 550, in launch_cemu
    Popen(cemu_args, cwd=str(util.get_cemu_dir()))
  File "/home/deck/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/deck/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine': 'wine'

**Comment by sks316** [comment]
You can't launch Cemu from BCML as it is now, it tries to launch from system Wine but on the Steam Deck, there is no system Wine.

You need to enable the mod pack in Cemu's graphics packs. If you don't see it there, try exporting the mod pack.
