### ISSUE TITLE
Python version not available?

### ISSUE THREAD

**Issue by OkamiTakahashi** [sks316/bcml-steamdeck#11]
Yes, hello, this github says that this Steam Deck version of BCML requires miniconda with Python 3.7. There IS no download for Miniconda with that version of Python anymore. What do I even do?

**Comment by sks316** [comment]
I wasn't aware they stopped distributing Miniconda for Python 3.7. [You should be able to download it from the Wayback Machine still.](http://web.archive.org/web/20230424121623/https://docs.conda.io/en/latest/miniconda.html)

Also I do want to note that BCML has been officially deprecated by its developers and [the new U-King Mod Manager is now recommended.](https://gamebanana.com/tools/12110) It has official Steam Deck support and I recommend using it if possible.

**Comment by OkamiTakahashi** [comment]
I'm aware of UKMM, but not every mod works for it rn as its still in beta, and I have a bit of a lengthy mod load order atm. I was able to get a file from a repository found on the site and download it, but now I'm just kind stuck not knowing how to install it; Linux is not exactly my strong point, and opening it in Konsole and pressing enter makes more text appear that I can't see all of nor can scroll to see the rest of (it just cuts off and says "more" highlighted in white. I've never done anything like this with my Steam Deck before, so this is all completely uncharted territory for me. (Edit: figured out the scrolling, it was R2, but hitting enter while running this in Konsole does not appear to have actually done jack squat as BCML still says Miniconda with Python 3.7 is still not installed.

**Comment by sks316** [comment]
You need to accept the Miniconda EULA before it will install. The installation script you downloaded should explain.
