### ISSUE TITLE
Encountering Issue

### ISSUE THREAD

**Issue by Dehunibun** [sks316/bcml-steamdeck#12]
[bcml_installer.log](https://github.com/user-attachments/files/16776828/bcml_installer.log)

**Comment by sks316** [comment]
Can you delete `/home/deck/miniconda3` and install [Miniconda with Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_23.1.0-1-Linux-x86_64.sh)? It seems like Python 3.7 no longer works for some reason.

**Comment by sks316** [comment]
Does installing [Miniconda with Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_23.1.0-1-Linux-x86_64.sh) resolve the issue? Please let me know. If I don't get a response, I may close this issue as resolved.

**Comment by sks316** [comment]
No response, closing as a duplicate of #7.
