### ISSUE TITLE
BCML failing to launch after install

### ISSUE THREAD

**Issue by FireXDragon007** [sks316/bcml-steamdeck#2]
grabbed the 3,7 version of python and installed bcml successfully but from there the application will not start, there were a few errors in the terminal output listed here

 
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1315  100  1315    0     0  27394      0 --:--:-- --:--:-- --:--:-- 27978
BCML will now be installed. This might take a bit.
modified      /home/deck/miniconda3/condabin/conda
modified      /home/deck/miniconda3/bin/conda
modified      /home/deck/miniconda3/bin/conda-env
no change     /home/deck/miniconda3/bin/activate
no change     /home/deck/miniconda3/bin/deactivate
no change     /home/deck/miniconda3/etc/profile.d/conda.sh
no change     /home/deck/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/deck/miniconda3/shell/condabin/Conda.psm1
no change     /home/deck/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/deck/miniconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /home/deck/miniconda3/etc/profile.d/conda.csh
no change     /home/deck/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/deck/miniconda3

  added / updated specs:
    - gcc

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.07.19~ --> conda-forge::ca-certificates-2022.9.24-ha878542_0 None
  certifi            pkgs/main/linux-64::certifi-2022.9.14~ --> conda-forge/noarch::certifi-2022.9.24-pyhd8ed1ab_0 None

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl              pkgs/main::openssl-1.1.1q-h7f8727e_0 --> conda-forge::openssl-1.1.1q-h166bdaf_0 None

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/deck/miniconda3

  added / updated specs:
    - pip

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.9.2~ --> pkgs/main::ca-certificates-2022.07.19-h06a4308_0 None
  certifi            conda-forge/noarch::certifi-2022.9.24~ --> pkgs/main/linux-64::certifi-2022.9.14-py39h06a4308_0 None
  openssl            conda-forge::openssl-1.1.1q-h166bdaf_0 --> pkgs/main::openssl-1.1.1q-h7f8727e_0 None

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
Collecting bcml
  Using cached bcml-3.9.26-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.9 MB)
Collecting pywebview~=3.6.3
  Using cached pywebview-3.6.3-py3-none-any.whl (351 kB)
Collecting pyqtwebengine
  Using cached PyQtWebEngine-5.15.6-cp37-abi3-manylinux1_x86_64.whl (230 kB)
Collecting xxhash~=1.4
  Using cached xxhash-1.4.4.tar.gz (54 kB)
  Preparing metadata (setup.py) ... done
Collecting botw-utils~=0.2.3
  Using cached botw_utils-0.2.3-py3-none-any.whl (3.5 MB)
Requirement already satisfied: requests~=2.27.1 in ./miniconda3/lib/python3.9/site-packages (from bcml) (2.27.1)
Collecting rstb>=1.2.2
  Using cached rstb-1.2.2-py3-none-any.whl (15 kB)
Collecting numpy~=1.19.3
  Using cached numpy-1.19.5-cp39-cp39-manylinux2010_x86_64.whl (14.9 MB)
Collecting oead~=1.2.4
  Using cached oead-1.2.4.post2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Collecting botw-havok~=0.3.18
  Using cached botw_havok-0.3.18-py3-none-any.whl (117 kB)
Collecting QtPy
  Using cached QtPy-2.2.0-py3-none-any.whl (82 kB)
Collecting aamp~=1.4.1
  Using cached aamp-1.4.1-py3-none-any.whl (337 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.7-cp37-abi3-manylinux1_x86_64.whl (8.4 MB)
Collecting PyYAML~=5.4.1
  Using cached PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
Collecting byml~=2.4.2
  Using cached byml-2.4.2-py3-none-any.whl (16 kB)
Collecting packaging~=21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Requirement already satisfied: colorama~=0.4.3 in ./miniconda3/lib/python3.9/site-packages (from botw-havok~=0.3.18->bcml) (0.4.4)
Requirement already satisfied: sortedcontainers~=2.0 in ./miniconda3/lib/python3.9/site-packages (from byml~=2.4.2->bcml) (2.4.0)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied: PyQtWebEngine-Qt5>=5.15.0 in ./miniconda3/lib/python3.9/site-packages (from pyqtwebengine->bcml) (5.15.2)
Collecting PyQt5-sip<13,>=12.11
  Using cached PyQt5_sip-12.11.0-cp39-cp39-manylinux1_x86_64.whl (357 kB)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in ./miniconda3/lib/python3.9/site-packages (from PyQt5->bcml) (5.15.2)
Requirement already satisfied: proxy-tools in ./miniconda3/lib/python3.9/site-packages (from pywebview~=3.6.3->bcml) (0.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/lib/python3.9/site-packages (from requests~=2.27.1->bcml) (2022.9.14)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./miniconda3/lib/python3.9/site-packages (from requests~=2.27.1->bcml) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/lib/python3.9/site-packages (from requests~=2.27.1->bcml) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./miniconda3/lib/python3.9/site-packages (from requests~=2.27.1->bcml) (1.26.8)
Building wheels for collected packages: xxhash
  Building wheel for xxhash (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/xxhash
      copying xxhash/__init__.py -> build/lib.linux-x86_64-3.9/xxhash
      running build_ext
      building '_xxhash' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/deps
      creating build/temp.linux-x86_64-3.9/deps/xxhash
      creating build/temp.linux-x86_64-3.9/src
      gcc -pthread -B /home/deck/miniconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/deck/miniconda3/include -I/home/deck/miniconda3/include -fPIC -O2 -isystem /home/deck/miniconda3/include -fPIC -Ideps/xxhash -I/home/deck/miniconda3/include/python3.9 -c deps/xxhash/xxhash.c -o build/temp.linux-x86_64-3.9/deps/xxhash/xxhash.o
      In file included from deps/xxhash/xxhash.h:242,
                       from deps/xxhash/xxhash.c:43:
      /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
          9 | # include_next <stdint.h>
            |                ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xxhash
  Running setup.py clean for xxhash
Failed to build xxhash
Installing collected packages: xxhash, PyYAML, pywebview, PyQt5-sip, pyparsing, oead, numpy, rstb, PyQt5, packaging, byml, botw-utils, botw-havok, aamp, QtPy, pyqtwebengine, bcml
  Running setup.py install for xxhash ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for xxhash did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running install
      /home/deck/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/xxhash
      copying xxhash/__init__.py -> build/lib.linux-x86_64-3.9/xxhash
      running build_ext
      building '_xxhash' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/deps
      creating build/temp.linux-x86_64-3.9/deps/xxhash
      creating build/temp.linux-x86_64-3.9/src
      gcc -pthread -B /home/deck/miniconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/deck/miniconda3/include -I/home/deck/miniconda3/include -fPIC -O2 -isystem /home/deck/miniconda3/include -fPIC -Ideps/xxhash -I/home/deck/miniconda3/include/python3.9 -c deps/xxhash/xxhash.c -o build/temp.linux-x86_64-3.9/deps/xxhash/xxhash.o
      In file included from deps/xxhash/xxhash.h:242,
                       from deps/xxhash/xxhash.c:43:
      /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
          9 | # include_next <stdint.h>
            |                ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> xxhash

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
mkdir: cannot create directory ‘/home/deck/.icons’: File exists
--2022-09-26 13:05:57--  https://github.com/sks316/bcml-steamdeck/raw/main/bcml.png
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sks316/bcml-steamdeck/main/bcml.png [following]
--2022-09-26 13:05:58--  https://raw.githubusercontent.com/sks316/bcml-steamdeck/main/bcml.png
SSL_INIT
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41498 (41K) [image/png]
Saving to: ‘/home/deck/.icons/bcml.png’

/home/deck/.icons/bcml.png                                 100%[========================================================================================================================================>]  40.53K  --.-KB/s    in 0.009s  

2022-09-26 13:05:58 (4.42 MB/s) - ‘/home/deck/.icons/bcml.png’ saved [41498/41498]

--2022-09-26 13:05:58--  https://github.com/sks316/bcml-steamdeck/raw/main/BCML.desktop
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sks316/bcml-steamdeck/main/BCML.desktop [following]
--2022-09-26 13:05:58--  https://raw.githubusercontent.com/sks316/bcml-steamdeck/main/BCML.desktop
SSL_INIT
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 541 [text/plain]
Saving to: ‘/home/deck/Desktop/BCML.desktop’

/home/deck/Desktop/BCML.desktop                            100%[========================================================================================================================================>]     541  --.-KB/s    in 0s      

2022-09-26 13:05:58 (77.5 MB/s) - ‘/home/deck/Desktop/BCML.desktop’ saved [541/541]

BCML is now installed. You can access it with the icon on your desktop, or through your application launcher.

after attempting to launch the application from the start menu or desktop shortcut im met with this error

![Screenshot_20220926_131508](https://user-images.githubusercontent.com/61310000/192350632-98453ade-d7da-4e46-87e0-3575ebac40eb.png)

**Comment by sks316** [comment]
You installed the wrong version of Miniconda. Despite what you say, the output tells me you installed Miniconda for Python 3.9. BCML currently fails to build on Python 3.9.
Delete /home/deck/miniconda3 and reinstall Miniconda, this time making sure to choose the right one.
