### ISSUE TITLE
Illegal Instruction (Core Dumped)

### ISSUE THREAD

**Issue by YourPalTaika** [sks316/bcml-steamdeck#3]
I'm not sure where even to begin with this issue.

On some mods, they extract and install fine, on others they immediately crash BCML with an Illegal Instruction error.

For example:

https://gamebanana.com/mods/406486 - This one works perfectly fine.

https://gamebanana.com/mods/409015 - This one Immediately crashes BCML.

Just before crashing, this is what I get in the terminal

Opening mod...
Identified mod: Npcsarmors1.8
Loading mod logs...
Assigned mod priority of 101
Moving mod to /home/taika/.config/bcml/mods/0101_Npcsarmors1.8...
VERBOSEInstalled 1 mods
Installed 1 mods
Cleansing old merges...
Refreshing merged mods...
Loading modded SARC list...
Merging 38 SARC files...
Illegal instruction (core dumped)

**Comment by sks316** [comment]
This is a BCML issue, not an installer issue. Open an issue at [NiceneNerd/BCML](https://github.com/NiceneNerd/BCML).
