### ISSUE TITLE
BCML not installing (downloaded miniconda 3.7)

### ISSUE THREAD

**Issue by ihastoes31** [sks316/bcml-steamdeck#4]
I installed miniconda 3.7 from [https://docs.conda.io/en/latest/miniconda.html#linux-installers](url), launched the install BCML script and got this back;

#!/bin/bash

_if test -f ~/miniconda3/condabin/conda &> /dev/null
then
    echo "BCML will now be installed. This might take a bit."
    zenity --info --text "BCML will now be installed. This might take a bit." --title "BCML Installer" --width=300 &> /dev/null
    ~/miniconda3/condabin/conda init
    ~/miniconda3/condabin/conda install -c conda-forge gcc -y
    ~/miniconda3/condabin/conda install pip -y
    ~/miniconda3/bin/python -m pip install bcml
    mkdir ~/.icons
    wget https://github.com/sks316/bcml-steamdeck/raw/main/bcml.png -O ~/.icons/bcml.png
    wget https://github.com/sks316/bcml-steamdeck/raw/main/BCML.desktop -O ~/Desktop/BCML.desktop
    chmod +x ~/Desktop/BCML.desktop
    cp ~/Desktop/BCML.desktop ~/.local/share/applications/BCML.desktop
    echo "BCML is now installed. You can access it with the icon on your desktop, or through your application launcher."
    zenity --info --text "BCML is now installed. You can access it with the icon on your desktop, or through your application launcher." --title "BCML Installer" --width=300 &> /dev/null
else
    echo "Miniconda is missing. Please install Miniconda with Python 3.7, then run this script again."
    zenity --error --text "Miniconda is missing. Please install Miniconda with Python 3.7, then run this script again." --title "BCML Installer" --width=300 &> /dev/null
fi
exit_

not sure what to do, tried reinstalling(miniconda and BCML installer), installing a different miniconda version(3.8)

**Comment by sks316** [comment]
That's just the text for the installer script. What exactly did you do, did you download the .desktop file from the releases page or did you download the bash script from the repository?

**Comment by ihastoes31** [comment]
under the releleases section i clicked the link and downloaded the .desktop file, then I made executab,e through properties and double clicked the .desktop file

**Comment by ihastoes31** [comment]
I got it to work! I believe I copied the text that showed when I clicked the application into Konsole, and it downloaded, no problems
