### ISSUE TITLE
Failed to symlink output folder

### ISSUE THREAD

**Issue by julio-kim** [sks316/bcml-steamdeck#8]
Hi!

I got an error installing the mod.
The cause of the error is "Failed to symlink output folder".
What can I do to fix this?

Currently installed version
* Miniconda Linux 64-bit (Python 3.7)

Thank you for a great application.

![Screenshot_20230410_232846](https://user-images.githubusercontent.com/5626425/230921524-d5755946-9f35-4028-b48b-6c83c4cccb53.png)

**Comment by ASmyrnyi** [comment]
try "python -m pip install bcml==3.10.4" in terminal (if pip is not installed, then "python -m ensurepip --upgrade")

**Comment by julio-kim** [comment]
Wow, it works!!!
Thank you for your quick reply~~:)
