### ISSUE TITLE
New Version of BCML breaks Steamdeck compatibility

### ISSUE THREAD

**Issue by Fr33hk** [sks316/bcml-steamdeck#9]
reverting to previous version fixes issue and restores functionality.

~/miniconda3/bin/python -m pip install bcml==3.9.23

Confirmed working on Steam OS 3.4.6

**Comment by sks316** [comment]
Apologies for my belatedness in getting to this issue, is the latest version still broken? I haven't had a chance to test this on my own.

**Comment by Ivyliott** [comment]
Sadly yes, it still is, at least for me. And because I have problems with the Terminal I have to wait for an Update that fixes this. Though this is only a Problem with the Steamdeck, BCML seems to be working just fine with everyone else.

**Comment by sks316** [comment]
Is this issue still occurring? If so, can you delete `/home/deck/miniconda3` and install [Miniconda with Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_23.1.0-1-Linux-x86_64.sh)? This fix appears to be working for some, and I'm not really sure why Python 3.7 isn't working for this anymore.

**Comment by sks316** [comment]
@Fr33hk @Ivyliott Does installing [Miniconda with Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_23.1.0-1-Linux-x86_64.sh) resolve the issue? Please let me know. If I don't get a response, I may close this issue as resolved.

**Comment by Fr33hk** [comment]
I did a complete reset and reinstall.  No issues noted
